### ISSUE TITLE
Incorrect account type mentioned

### ISSUE THREAD

**Issue by bksarthak** [awsdocs/aws-codecommit-user-guide#11]
Step 4 on this page
For example, run the following command to create a default AWS CLI profile that you use to access AWS resources in **AccountA** in US East (Ohio) (us-east-2):
The bold section above should be AccountB

**Comment by AWS-SF** [comment]
Thank you for the issue! The resources are in AccountA. You're configuring a profile to access those resources (the repository) in AccountA from AccountB.
