### ISSUE TITLE
Commands fail when running in bash

### ISSUE THREAD

**Issue by raonitimo** [awsdocs/aws-codecommit-user-guide#12]
When using double quotes on command git config --global credential.helper "!aws codecommit credential-helper --profile MyCrossAccountAccessProfile $@" bash will expand [1] !aws to the last command ran starting with "aws". Replacing it with single quotes fixes the command.

References:
[1] Bash history expansion - https://www.gnu.org/software/bash/manual/html_node/History-Interaction.html#History-Interaction

**Comment by AWS-SF** [comment]
I believe this varies by operating system and editor of choice.
