### ISSUE TITLE
Git protocol and permissions

### ISSUE THREAD

**Issue by martinoneutrino** [awsdocs/aws-codecommit-user-guide#20]
Please explain the seeming discrepancy relating to branch permissions using git:

**Git is restricted by policy**
https://github.com/awsdocs/aws-codecommit-user-guide/blob/master/doc_source/how-to-conditional-branch.md
> By default, any CodeCommit repository user who has sufficient permissions to push code to the repository can contribute to any branch in that repository. This is true no matter how you add a branch to the repository: by using the console, the command line, or Git.
...
> From the terminal or command line, create a commit on the branch where the restrictions apply, and then push that commit to the CodeCommit repository. You should see an error message. Commits and pushes made from other branches should work as usual.

**Git not restricted by policy** 
https://github.com/awsdocs/aws-codecommit-user-guide/blob/master/doc_source/auth-and-access-control-permissions-reference.md#aa-branches
> The following permissions allow or deny actions on branches in CodeCommit repositories. These permissions pertain only to actions performed in the CodeCommit console and with the CodeCommit API, and to commands performed using the AWS CLI. They do not pertain to similar actions that can be performed using the Git protocol.

**Comment by AWS-SF** [comment]
Hi there,

The conditional branch example is restricting actions based on a matching conditional statement with branch names:

"Condition": {
                "StringEqualsIfExists": {
                    "codecommit:References": [
                        "refs/heads/master", 
                        "refs/heads/prod"
                     ]
                },

It's denying pushing changes to the branches that match those strings with "codecommit:GitPush", among other actions. It's also denying deleting branches that match those strings with "codecommit:DeleteBranch".  A user could still use Git to delete a branch locally, as this policy does not control git branch commands on the local machine.  However, when the user attempts to push the changes to the CodeCommit repository, the policy would apply.

**Comment by martinoneutrino** [comment]
It still isn’t clear why the second seems to contradict the first. I will need to setup and test myself.
