### ISSUE TITLE
Credential Helper Path for CLI v2

### ISSUE THREAD

**Issue by jmino** [awsdocs/aws-codecommit-user-guide#22]
Update the path for CLI v2.

`[credential]    
    helper = !"\C:\\Program Files\\Amazon\\AWSCLI\\bin\\aws.cmd\" codecommit credential-helper $@ 
    UseHttpPath = true`

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
