### ISSUE TITLE
The troubleshooting guide for Access error "User is not authorized for the KMS default key" is misleading

### ISSUE THREAD

**Issue by radnov** [awsdocs/aws-codecommit-user-guide#23]
The "**Possible fixes**" within [the troubleshooting guide](https://docs.aws.amazon.com/codecommit/latest/userguide/troubleshooting-cs.html#troubleshooting-ae3) for Access Error `User is not authorized for the KMS default master key for CodeCommit 'alias/aws/codecommit' in your account` no longer seems to be valid for the current UI. There's no "Encryption Keys" reference within the IAM console.

Following the [link](https://docs.aws.amazon.com/codecommit/latest/userguide/encryption.html) at the end of the **Possible fixes** is enough to guide the user in the right direction for fixing the issue.

**Comment by AWS-SF** [comment]
Thank you for raising this issue!  The KMS console is indeed now independent of IAM. A fix is in progress.
