### ISSUE TITLE
typo: doc_source/how-to-notify-lambda-cc.md "- -cli-input-json"

### ISSUE THREAD

**Issue by thesuavehog** [awsdocs/aws-codecommit-user-guide#26]
https://docs.aws.amazon.com/codecommit/latest/userguide/how-to-notify-lambda-cc.html#how-to-notify-lambda-create-function-perm

current:
`aws lambda add-permission - -cli-input-json file://AllowAccessfromMyDemoRepo.json`

There is an extra space between the dashes.
"- -cli-input-json" should be "--cli-input-json"

**Comment by AWS-SF** [comment]
Thank you for bringing up this issue!  A fix is in progress.

**Comment by AWS-SF** [comment]
The issue has been fixed. Thanks again for the contribution!
