### ISSUE TITLE
Get raw file

### ISSUE THREAD

**Issue by apmartins85** [awsdocs/aws-codecommit-user-guide#28]
Hi guys,

Is it possible to get a simple raw (i.e. yaml file) from an ec2 instance via curl?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
