### ISSUE TITLE
Pull request is not updating after migration

### ISSUE THREAD

**Issue by vinayhegde105** [awsdocs/aws-codecommit-user-guide#37]
Migrating from github to codecommit is successfully migrated codes and branches but not pull request.
Do we have any other way to migrate everything?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
