### ISSUE TITLE
issues with the code commit cloning

### ISSUE THREAD

**Issue by Raghuveer123** [awsdocs/aws-codecommit-user-guide#5]
I have a account integrated with the MFA,I am unable to clone the repo even though I add the public key to the my user id.Can you please help out me with this issue and I have admin privileges for this account

**Comment by AWS-SF** [comment]
Hi there,

This is the repository for the AWS CodeCommit User Guide, and not a secure help channel. I've hidden your customer account ID from your message. I've also forwarded your information and your question to the service team.

When encountering issues with CodeCommit, try posting your issue in the [AWS CodeCommit forum](https://forums.aws.amazon.com/forum.jspa?forumID=189&start=0).

I hope this helps!
